### ISSUE TITLE
Rom Building Script Missing

### ISSUE THREAD

**Issue by JackWitherell** [MiSTer-devel/Arcade-DonkeyKong_MiSTer#14]
The latest commit removes the files specified in the readme for building the rom file. Assuming this was done in error?

**Comment by sorgelig** [comment]
Use MRA, read the forum

**Comment by JackWitherell** [comment]
Can I get any more information? I have no idea what MRA is nor do I know what forum you're referring to. There's no mention of either within the scope of this repo.

readme still has misleading/inaccurate information.

**Comment by sorgelig** [comment]
http://www.atari-forum.com/viewtopic.php?f=117&t=32481

Readme will be updated later.
