### ISSUE TITLE
Donkey Kong alternatives not working

### ISSUE THREAD

**Issue by evidencedj** [MiSTer-devel/Arcade-DonkeyKong_MiSTer#25]
Since the new version of Donkey Kong 20210112 most of the alternatives are not working anymore. I only get yellow ish graphics. 
When I fallback to Version 20200108 these alternatives run fine. A friend of mine has the same problem. The mame and hbmame roms are from update_all.

![20210205_162433](https://user-images.githubusercontent.com/33894818/107054478-7644a200-67d0-11eb-86db-7ec7ffddd1b6.jpg)

**Comment by sorgelig** [comment]
only MRAs from current repository are guaranteed to work. Any MRA downloaded from anywhere else are not guaranteed to work as format could be changed. 
It's not an issue of this core/code. You need to report to those who support alternative MRAs.

**Comment by evidencedj** [comment]
Issue opened in [https://github.com/MiSTer-devel/MRA-Alternatives_MiSTer](url)
