### ISSUE TITLE
hbmame roms not working

### ISSUE THREAD

**Issue by jstavats** [MiSTer-devel/Arcade-DonkeyKong_MiSTer#26]
Hi, something in the 2021-01-12 core release has caused a number of the homebrew roms to stop working correctly. For example the rainbow donkey kong comes up with the screen full of orange and beige garbage...

**Comment by jstavats** [comment]
It looks like the rom layout has changed in the mra. Matching the new latout in the hbrom mra allowed the them to start working. Is the new layout correct now?

**Comment by sorgelig** [comment]
If MRA isn't from this repository, then you have to report to author of that MRA to update/fix. 
Not here.

**Comment by jstavats** [comment]
Yep, I wasn’t sure it was mra related when I entered it. I tracked it down and submitted a PR with fixes in the alternatives github.
