### ISSUE TITLE
Radar Scope Problems

### ISSUE THREAD

**Issue by skeeter57** [MiSTer-devel/Arcade-DonkeyKong_MiSTer#37]
Radar Scope locks up on the title screen with garbled graphics and the controls don't work. I rolled back to the 20210824 rbf and the issues are gone. Thank you.

**Comment by JimmyStones** [comment]
Sounds like it could be a corrupted hiscore save.  Can you try deleting "/media/fat/config/nvram/Radar Scope.nvm" if you have it and trying the latest version again?

**Comment by skeeter57** [comment]
Thanks for the fast reply and yup, that was it. All good now, thank you.
