### ISSUE TITLE
Merge code for better sounds

### ISSUE THREAD

**Issue by Robgus79** [MiSTer-devel/Arcade-DonkeyKong_MiSTer#58]
Can someone please merge Schendel's code https://github.com/pvanschendel/Arcade-DonkeyKong_MiSTer with the current core for better sounds.

Topic for reference: https://misterfpga.org/viewtopic.php?p=70733#p70733

Thanks!

**Comment by sorgelig** [comment]
try this build with merged changes:
[Arcade-DonkeyKong_t1.zip](https://github.com/MiSTer-devel/Arcade-DonkeyKong_MiSTer/files/11051881/Arcade-DonkeyKong_t1.zip)

**Comment by sorgelig** [comment]
Is it worse now?

**Comment by Robgus79** [comment]
Thanks! I had music when I tried it just now but it sounds like it did before Schendel implemented this, which in my opinion is better: https://github.com/pvanschendel/Arcade-DonkeyKong_MiSTer/blob/Improve_synthesizer_sound/releases/Arcade-DonkeyKong_20221120.rbf

**Comment by sorgelig** [comment]
> Thanks! I had music when I tried it just now but it sounds like it did before Schendel implemented this, which in my opinion is better: https://github.com/pvanschendel/Arcade-DonkeyKong_MiSTer/blob/Improve_synthesizer_sound/releases/Arcade-DonkeyKong_20221120.rbf

i didn't understand your message.

**Comment by Robgus79** [comment]
What I meant was that the latest official update that came a few days ago still has music in my setup when I tried it today. (Lagomorph said that he didn't have music) Though it is still the "older" version of music that was before Schendel implemented his sounds. 

Hope it clarifies. Thanks!

**Comment by lagomorph** [comment]
> What I meant was that the latest official update that came a few days ago still has music in my setup when I tried it today. (Lagomorph said that he didn't have music) Though it is still the "older" version of music that was before Schendel implemented his sounds.
> 
> Hope it clarifies. Thanks!

No. The code you wished to be committed in this PR is what I'm referring to. Why would I refer to something else? You obviously did not test what's in this PR.

**Comment by Robgus79** [comment]
No I didn't. I tested the core after I ran the update script. Thought it was the same.

**Comment by sorgelig** [comment]
after release 20221120 there were 2 additional changes. May be they introduced regression.

**Comment by thorr2** [comment]
I also tried the Arcade-DonkeyKong_t1.zip above and most of the sound is missing.  schendel's version is great, so hopefully this can get properly integrated with the latest updates.  I personally like the newer version of the walking sound.  This is what it should sound like, and it is pretty close to my ears.  https://youtu.be/tJagEKVJ8x4?t=56

**Comment by sorgelig** [comment]
If your change fixes some problems then you are welcome to do a pull request

**Comment by Robgus79** [comment]
Thanks a lot for this, wonderful work! For some reason the general volume is lower in this version than the previous that I had... or is that just me?

**Comment by sorgelig** [comment]
Looks like fixed. Thanks @pvanschendel
